    DEVICE ZXSPECTRUM48

message
    dm "                                "
    dm " WELKAM WORLD 2 ANOTHA CRS WORK "
    dm "                                "
    dm "   THE  F L I N T S T O N E S   "
    dm "      -FRED IN MAGIC WOOD-      "
    dm "                                "
    dm "CREDITZ:                        "
    dm "--------------------------------"
    dm "INTRO IDEA...............MAD/CRS"
    dm "      MUZAK...........HAZARD/PHT"
    dm "      CODES,GFX,FNT......MAD/CRS"
    dm "GAME IDEA................MAD/CRS"
    dm "     SCREEN..............SPY/CRS"
    dm "     MUZAK..........BENN DAGLISH"
    dm "     CODES,GFX,FNT.......MAD/CRS"
    dm "MORAL SUPPORT............SPY/CRS"
    dm "--------------------------------"
    dm "                                "
    dm "GREETINGS:     IN ALPHABET ORDER"
    dm " (LV) CRUSHERS FIRST OF COZ!    "
    dm "     HUNTER,NOART AND WARLORD   "
    dm "     HI GUYS !!!!!!!!           "
    dm "      PHANTASY : DEPREDATOR,    "
    dm "     RAVER,HAZARD AND OTHERS    "
    dm "     (MO DEMOS PLEASE!)         "
    dm "      ALFA GROUP,ANOTHER REALITY"
    dm "      ENERGY,WAVE SOFT :        "
    dm "     CIRCUL,ELIS,MERKURJEV      "
    dm " (LV,ESS,RUS,BU,UA,SK,CZ,POL)   "
    dm "     3SC,7 GOODS,AGENT X,ANTARES"
    dm "     POWER OF SOUND,BUSY&NORO   "
    dm "     CLAW,CODE BUSTERS,CONDOR   "
    dm "     DIGITAL REALITY,DIAMOND    "
    dm "     E-MAGE,EXTACY #3,EXTREME   "
    dm "     FATALITY,FLASH,ILLUSION    "
    dm "     K3L,MAFIA,PROGRESS,PROPHECY"
    dm "     REACTION,REAL MASTERS,RUSH "
    dm "     (D.M.S AND OTEHERS),STALKER"
    dm "     ZER0 AND ALL SP USERS..    "
    dm "                                "
    dm " COOOOOL !! DON'T YA THINK SO ??"
    dm " 2/3 MOVING + 1/3 ANDING & ORING"
    dm " PARTS OF WHOLE SCREEN + ONE P.T"
    dm " PLAY ROUTINE ALL DIS IN DE SAME"
    dm " TIME ON ONE (!!) SCR/RAM PAGE !"
    dm "(CRAK ! AND U WILL SEE DAT !!!!)"
    dm "                                "
    dm "                                "
    dm " (C) CRUSHERS 1997/98           "
    dm "                                "
    dm "       C YA SOON !!!!           "
    dm "                                "
    dm "                                "
    dm "                                "
    dm "                                "
    dm "                                "
    dm "                                "
    dm "                                "
    dm "                                "
    dm "P.S. TRY TO FIND CHEAT MODE !!! "
    dm "                                "
    db 0x0

